name: flutter_application_prueba
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Supabase para Flutter
  supabase_flutter: ^2.5.1

  # Nuevas dependencias solicitadas
  file_picker: ^10.2.0
  geolocator: ^14.0.2
  url_launcher: ^6.2.1
  image_picker: ^1.0.7
  image: ^4.0.17
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
